# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
            ],
        ),
    ]
