# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_task_time_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_modified',
            field=models.DateTimeField(),
        ),
    ]
